packages:
  # Applications
  - "apps/*"

  # Shared libraries
  - "packages/*"

  # Internal tooling
  # - "tooling/*"

  # Infrastructure packages (if any become Node packages)
  # - "infra/*"

  # Automation / generators
  # - "scripts/*"

  # Exclude tests
  - "!**/test/**"

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "prisma"
  - "esbuild"
  - "sharp"
  - "unrs-resolver"

ignoredBuiltDependencies:
  - esbuild

allowBuilds:
  esbuild: true
