// ─────────────────────────────────────────────────────────────────
// errors/codes.ts
// ─────────────────────────────────────────────────────────────────
// Single source of truth for every error code in the system.
//
// Rules:
//   • Namespaced by domain     (AUTH_, DEVICE_, ORG_, PROJECT_…)
//   • SCREAMING_SNAKE_CASE     (matches industry convention)
//   • Stable across releases   (clients / mobile apps depend on these)
//   • Never renamed or removed — deprecate and add new instead
//   • Never reused for two different meanings (see note on DEVICE_* vs
//     AUTH_DEVICE_* below — device *registry* vs device *session*)
//
// When adding a new module (sync, appInit, billing, notifications…)
// add a new fenced section below, keep codes grouped, and update
// messages.ts + a matching file under errors/catalog/*.ts.
// ─────────────────────────────────────────────────────────────────

export const ErrorCode = {
  // ── Generic HTTP ──────────────────────────────────────────────
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  CONFLICT: "CONFLICT",
  UNPROCESSABLE: "UNPROCESSABLE",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  INTERNAL: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  // ── Validation ────────────────────────────────────────────────
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INVALID_PARAM: "INVALID_PARAM",
  MISSING_FIELD: "MISSING_FIELD",

  // roles
  ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
  ROLE_ALREADY_EXISTS: "ROLE_ALREADY_EXISTS",
  ROLE_CREATE_FAILED: "ROLE_CREATE_FAILED",
  ROLE_UPDATE_FAILED: "ROLE_UPDATE_FAILED",
  ROLE_DELETE_FAILED: "ROLE_DELETE_FAILED",
  ROLE_SYSTEM_PROTECTED: "ROLE_SYSTEM_PROTECTED",

  PERMISSION_NOT_FOUND: "PERMISSION_NOT_FOUND",
  PERMISSION_ALREADY_EXISTS: "PERMISSION_ALREADY_EXISTS",
  PERMISSION_CREATE_FAILED: "PERMISSION_CREATE_FAILED",
  PERMISSION_UPDATE_FAILED: "PERMISSION_UPDATE_FAILED",
  PERMISSION_DELETE_FAILED: "PERMISSION_DELETE_FAILED",

  ROLE_PERMISSION_ALREADY_EXISTS: "ROLE_PERMISSION_ALREADY_EXISTS",
  ROLE_PERMISSION_NOT_FOUND: "ROLE_PERMISSION_NOT_FOUND",

  USER_ROLE_ALREADY_EXISTS: "USER_ROLE_ALREADY_EXISTS",
  USER_ROLE_NOT_FOUND: "USER_ROLE_NOT_FOUND",

  AUTH_INSUFFICIENT_PERMISSION: "AUTH_INSUFFICIENT_PERMISSION",
  AUTH_PERMISSION_REQUIRED: "AUTH_PERMISSION_REQUIRED",

  // ── Auth: tokens ──────────────────────────────────────────────
  AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_REFRESH_TOKEN_INVALID: "AUTH_REFRESH_TOKEN_INVALID",
  AUTH_REFRESH_TOKEN_EXPIRED: "AUTH_REFRESH_TOKEN_EXPIRED",
  AUTH_REFRESH_TOKEN_REUSED: "AUTH_REFRESH_TOKEN_REUSED",

  // ── Auth: login session ──────────────────────────────────────
  AUTH_SESSION_NOT_FOUND: "AUTH_SESSION_NOT_FOUND",
  AUTH_SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
  AUTH_SESSION_REVOKED: "AUTH_SESSION_REVOKED",

  // ── Auth: OTP ─────────────────────────────────────────────────
  AUTH_OTP_INVALID: "AUTH_OTP_INVALID",
  AUTH_OTP_EXPIRED: "AUTH_OTP_EXPIRED",
  AUTH_OTP_RATE_LIMIT: "AUTH_OTP_RATE_LIMIT",
  AUTH_OTP_CREATE_FAILED: "AUTH_OTP_CREATE_FAILED",
  AUTH_OTP_DELIVERY_FAILED: "AUTH_OTP_DELIVERY_FAILED",
  AUTH_OTP_DELIVERY_UNAVAILABLE: "AUTH_OTP_DELIVERY_UNAVAILABLE",

  // ── Auth: password ────────────────────────────────────────────
  AUTH_PASSWORD_TOO_WEAK: "AUTH_PASSWORD_TOO_WEAK",
  AUTH_PASSWORD_REQUIRED: "AUTH_PASSWORD_REQUIRED",
  AUTH_PASSWORD_ALREADY_SET: "AUTH_PASSWORD_ALREADY_SET",
  AUTH_CURRENT_PASSWORD_INVALID: "AUTH_CURRENT_PASSWORD_INVALID",
  AUTH_RESET_TOKEN_INVALID: "AUTH_RESET_TOKEN_INVALID",
  AUTH_RESET_TOKEN_EXPIRED: "AUTH_RESET_TOKEN_EXPIRED",
  AUTH_RESET_TOKEN_ALREADY_USED: "AUTH_RESET_TOKEN_ALREADY_USED",
  AUTH_MUST_RESET_PASSWORD: "AUTH_MUST_RESET_PASSWORD",

  // ── Auth: OAuth / external providers ─────────────────────────
  AUTH_OAUTH_TOKEN_INVALID: "AUTH_OAUTH_TOKEN_INVALID",
  AUTH_OAUTH_UNAVAILABLE: "AUTH_OAUTH_UNAVAILABLE",
  AUTH_INVALID_PROVIDER: "AUTH_INVALID_PROVIDER",
  AUTH_PROVIDER_NOT_FOUND: "AUTH_PROVIDER_NOT_FOUND",
  AUTH_PROVIDER_CREATE_FAILED: "AUTH_PROVIDER_CREATE_FAILED",
  AUTH_PROVIDER_NOT_LINKED: "AUTH_PROVIDER_NOT_LINKED",
  AUTH_PROVIDER_ALREADY_LINKED: "AUTH_PROVIDER_ALREADY_LINKED",

  // ── Auth: credentials ─────────────────────────────────────────
  AUTH_CREDENTIALS_NOT_FOUND: "AUTH_CREDENTIALS_NOT_FOUND",
  AUTH_CREDENTIALS_CREATE_FAILED: "AUTH_CREDENTIALS_CREATE_FAILED",
  AUTH_CREDENTIALS_ALREADY_EXIST: "AUTH_CREDENTIALS_ALREADY_EXIST",
  AUTH_LOGIN_HISTORY_CREATE_FAILED: "AUTH_LOGIN_HISTORY_CREATE_FAILED",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",

  // ── Auth: MFA ─────────────────────────────────────────────────
  AUTH_MFA_ENROLLMENT_EXPIRED: "AUTH_MFA_ENROLLMENT_EXPIRED",
  AUTH_MFA_ALREADY_ENABLED: "AUTH_MFA_ALREADY_ENABLED",
  AUTH_MFA_NOT_ENABLED: "AUTH_MFA_NOT_ENABLED",
  AUTH_MFA_INVALID: "AUTH_MFA_INVALID",
  // ── Auth: RBAC ────────────────────────────────────────────────
  AUTH_ROLE_FORBIDDEN: "AUTH_ROLE_FORBIDDEN",
  AUTH_ROLE_REQUIRED: "AUTH_ROLE_REQUIRED",
  AUTH_PERMISSION_DENIED: "AUTH_PERMISSION_DENIED",

  // ── Auth: account / impersonation ────────────────────────────
  AUTH_ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED",
  AUTH_IMPERSONATION_NOT_ACTIVE: "AUTH_IMPERSONATION_NOT_ACTIVE",

  // ── Auth: device session (the trusted-device / refresh binding,
  //          NOT the device registry entity below) ───────────────
  AUTH_DEVICE_REVOKED: "AUTH_DEVICE_REVOKED",
  AUTH_DEVICE_EXPIRED: "AUTH_DEVICE_EXPIRED",
  AUTH_DEVICE_REFRESH_TOKEN_MISMATCH: "AUTH_DEVICE_REFRESH_TOKEN_MISMATCH",

  AUTH_SECURITY_EVENT_CREATE_FAILED: "AUTH_SECURITY_EVENT_CREATE_FAILED",

  // ── API keys ──────────────────────────────────────────────────
  API_KEY_NOT_FOUND: "API_KEY_NOT_FOUND",
  API_KEY_INVALID: "API_KEY_INVALID",
  API_KEY_EXPIRED: "API_KEY_EXPIRED",
  API_KEY_REVOKED: "API_KEY_REVOKED",
  API_KEY_CREATE_FAILED: "API_KEY_CREATE_FAILED",

  // ── Device registry (physical/browser device records) ──────────
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  DEVICE_FINGERPRINT_REQUIRED: "DEVICE_FINGERPRINT_REQUIRED",
  DEVICE_ALREADY_EXISTS: "DEVICE_ALREADY_EXISTS",
  DEVICE_CREATE_FAILED: "DEVICE_CREATE_FAILED",
  DEVICE_LIMIT_EXCEEDED: "DEVICE_LIMIT_EXCEEDED",

  // ── User ──────────────────────────────────────────────────────
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_CREATE_FAILED: "USER_CREATE_FAILED",
  USER_INACTIVE: "USER_INACTIVE",
  USER_EMAIL_ALREADY_EXISTS: "USER_EMAIL_ALREADY_EXISTS",
  USER_PHONE_ALREADY_EXISTS: "USER_PHONE_ALREADY_EXISTS",
  USER_EMAIL_NOT_VERIFIED: "USER_EMAIL_NOT_VERIFIED",
  USER_PHONE_NOT_VERIFIED: "USER_PHONE_NOT_VERIFIED",
  ONBOARDING_INCOMPLETE: "ONBOARDING_INCOMPLETE",

  // ── Profile ───────────────────────────────────────────────────
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  PROFILE_ALREADY_EXISTS: "PROFILE_ALREADY_EXISTS",
  PROFILE_INCOMPLETE: "PROFILE_INCOMPLETE",

  // ── Organization ──────────────────────────────────────────────
  ORGANIZATION_NOT_FOUND: "ORGANIZATION_NOT_FOUND",
  ORGANIZATION_ALREADY_EXISTS: "ORGANIZATION_ALREADY_EXISTS",
  ORGANIZATION_ACCESS_DENIED: "ORGANIZATION_ACCESS_DENIED",
  ORGANIZATION_CREATE_FAILED: "ORGANIZATION_CREATE_FAILED",

  ORG_INVITE_NOT_FOUND: "ORG_INVITE_NOT_FOUND",
  ORG_INVITE_EXPIRED: "ORG_INVITE_EXPIRED",
  ORG_INVITE_ALREADY_ACCEPTED: "ORG_INVITE_ALREADY_ACCEPTED",

  ORG_MEMBER_CREATE_FAILED: "ORG_MEMBER_CREATE_FAILED",
  ORG_MEMBER_NOT_FOUND: "ORG_MEMBER_NOT_FOUND",
  ORG_MEMBER_ALREADY_EXISTS: "ORG_MEMBER_ALREADY_EXISTS",
  ORG_MEMBER_LAST_OWNER: "ORG_MEMBER_LAST_OWNER",

  ORG_WORKSPACE_CREATE_FAILED: "ORG_WORKSPACE_CREATE_FAILED",

  // ── Project ───────────────────────────────────────────────────
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECT_ALREADY_EXISTS: "PROJECT_ALREADY_EXISTS",
  PROJECT_ACCESS_DENIED: "PROJECT_ACCESS_DENIED",
  PROJECT_MEMBER_NOT_FOUND: "PROJECT_MEMBER_NOT_FOUND",
  PROJECT_MEMBER_ALREADY_EXISTS: "PROJECT_MEMBER_ALREADY_EXISTS",
  PROJECT_ENVIRONMENT_NOT_FOUND: "PROJECT_ENVIRONMENT_NOT_FOUND",
  PROJECT_ENVIRONMENT_ALREADY_EXISTS: "PROJECT_ENVIRONMENT_ALREADY_EXISTS",
  ENVIRONMENT_VARIABLE_NOT_FOUND: "ENVIRONMENT_VARIABLE_NOT_FOUND",
  ENVIRONMENT_SECRET_NOT_FOUND: "ENVIRONMENT_SECRET_NOT_FOUND",

  // ── Provider integration (e.g. GitHub/GitLab connections) ──────
  PROVIDER_CONNECTION_NOT_FOUND: "PROVIDER_CONNECTION_NOT_FOUND",
  PROVIDER_CONNECTION_ALREADY_EXISTS: "PROVIDER_CONNECTION_ALREADY_EXISTS",
  PROVIDER_CONNECTION_INVALID: "PROVIDER_CONNECTION_INVALID",
  REPOSITORY_NOT_FOUND: "REPOSITORY_NOT_FOUND",
  REPOSITORY_ALREADY_LINKED: "REPOSITORY_ALREADY_LINKED",
  REPOSITORY_ACCESS_DENIED: "REPOSITORY_ACCESS_DENIED",

  // ── Workspace ─────────────────────────────────────────────────
  WORKSPACE_NOT_FOUND: "WORKSPACE_NOT_FOUND",
  WORKSPACE_ALREADY_EXISTS: "WORKSPACE_ALREADY_EXISTS",
  WORKSPACE_ACCESS_DENIED: "WORKSPACE_ACCESS_DENIED",
  WORKSPACE_LIMIT_EXCEEDED: "WORKSPACE_LIMIT_EXCEEDED",

  // ── Sync (new module — extend as sync engine grows) ─────────────
  SYNC_FAILED: "SYNC_FAILED",
  SYNC_CONFLICT: "SYNC_CONFLICT",
  SYNC_IN_PROGRESS: "SYNC_IN_PROGRESS",
  SYNC_SOURCE_UNAVAILABLE: "SYNC_SOURCE_UNAVAILABLE",

  // ── App init / bootstrap (new module) ────────────────────────
  APP_INIT_FAILED: "APP_INIT_FAILED",
  APP_CONFIG_MISSING: "APP_CONFIG_MISSING",
  APP_VERSION_UNSUPPORTED: "APP_VERSION_UNSUPPORTED",

  // ── Payment ───────────────────────────────────────────────────
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_AMOUNT_MISMATCH: "PAYMENT_AMOUNT_MISMATCH",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_ALREADY_CAPTURED: "PAYMENT_ALREADY_CAPTURED",
  PAYMENT_GATEWAY_ERROR: "PAYMENT_GATEWAY_ERROR",
  ESCROW_NOT_HELD: "ESCROW_NOT_HELD",
  REFUND_FAILED: "REFUND_FAILED",
  PAYOUT_FAILED: "PAYOUT_FAILED",

  // ── Dispute ───────────────────────────────────────────────────
  DISPUTE_NOT_FOUND: "DISPUTE_NOT_FOUND",
  DISPUTE_ALREADY_CLOSED: "DISPUTE_ALREADY_CLOSED",

  // ── Upload ────────────────────────────────────────────────────
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  FILE_TYPE_NOT_ALLOWED: "FILE_TYPE_NOT_ALLOWED",
  UPLOAD_FAILED: "UPLOAD_FAILED",

  // ── Database ──────────────────────────────────────────────────
  DB_UNIQUE_VIOLATION: "DB_UNIQUE_VIOLATION",
  DB_FOREIGN_KEY: "DB_FOREIGN_KEY",
  DB_CONNECTION: "DB_CONNECTION",
  DB_TIMEOUT: "DB_TIMEOUT",

  AUTH_PASSKEY_LIMIT_REACHED: "AUTH_PASSKEY_LIMIT_REACHED",
  AUTH_PASSKEY_REVOKED: "AUTH_PASSKEY_REVOKED",
  AUTH_PASSKEY_CLONE_DETECTED: "AUTH_PASSKEY_CLONE_DETECTED",
  AUTH_PASSKEY_COUNTER_MISMATCH: "AUTH_PASSKEY_COUNTER_MISMATCH",
  AUTH_PASSKEY_CHALLENGE_INVALID: "AUTH_PASSKEY_CHALLENGE_INVALID",
  AUTH_PASSKEY_CHALLENGE_EXPIRED: "AUTH_PASSKEY_CHALLENGE_EXPIRED",
  AUTH_PASSKEY_VERIFICATION_FAILED: "AUTH_PASSKEY_VERIFICATION_FAILED",
  AUTH_PASSKEY_REGISTRATION_FAILED: "AUTH_PASSKEY_REGISTRATION_FAILED",
  AUTH_PASSKEY_INVALID: "AUTH_PASSKEY_INVALID",
  AUTH_PASSKEY_ALREADY_EXISTS: "AUTH_PASSKEY_ALREADY_EXISTS",
  AUTH_PASSKEY_NOT_FOUND: "AUTH_PASSKEY_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];