import { sql } from "drizzle-orm";
import { check, jsonb, pgTable, uniqueIndex, uuid } from "drizzle-orm/pg-core";

import { timestamps } from "../common/timestamps";
import { projects } from "./projects";

export interface ProjectSettings {
  general?: {
    defaultBranch?: string;
    timezone?: string;
    archived?: boolean;
  };

  repository?: {
    autoSync?: boolean;
    syncIntervalMinutes?: number;
    autoDiscoverRepositories?: boolean;
    defaultProvider?: "GITHUB" | "GITLAB" | "AZURE_DEVOPS" | "BITBUCKET";
  };

  ai?: {
    enabled?: boolean;
    autoReview?: boolean;
    autoSummarizePRs?: boolean;
    autoGenerateDocs?: boolean;
    autoDetectComponents?: boolean;
    indexingEnabled?: boolean;
  };

  security?: {
    secretScanning?: boolean;
    dependencyScanning?: boolean;
    codeScanning?: boolean;
    allowPublicRepositories?: boolean;
  };

  notifications?: {
    email?: boolean;
    slack?: boolean;
    teams?: boolean;
    discord?: boolean;
  };

  deployments?: {
    autoDeploy?: boolean;
    protectedBranches?: string[];
  };

  metadata?: Record<string, unknown>;
}

export const projectSettings = pgTable(
  "project_settings",
  {
    id: uuid("project_settings_id").defaultRandom().primaryKey(),

    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),

    settings: jsonb("settings")
      .$type<ProjectSettings>()
      .notNull()
      .default(sql`'{}'::jsonb`),

    ...timestamps,
  },
  (table) => [
    uniqueIndex("project_settings_project_unique").on(table.projectId),

    check(
      "project_settings_json_object_check",
      sql`jsonb_typeof(${table.settings}) = 'object'`,
    ),
  ],
);
